name: Exploring Variables and Secrets
on: push

# environment variables at the WORKFLOW level
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker: 
        # environment variables at the JOB level
        # env:
        #     CONTAINER_REGISTRY: docker.io
        #     DOCKER_USERNAME: siddharth1
        #     IMAGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
        # environments variables at the STEP level
        #   env:
        #     CONTAINER_REGISTRY: docker.io
        #     DOCKER_USERNAME: siddharth1
        #     IMAGE_NAME: github-actions-nginx
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker Login
        # environments variables at the STEP level
          env:
        #     DOCKER_USERNAME: siddharth1
            DOCKER_PASSWORD: s3cUrePaSsw0rd
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker Publish
        # environments variables at the STEP level
        #   env:
            # CONTAINER_REGISTRY: docker.io
            # DOCKER_USERNAME: siddharth1
            # IMAGE_NAME: github-actions-nginx
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        # environment variables at the JOB level
        # env:
        #     CONTAINER_REGISTRY: docker.io
        #     DOCKER_USERNAME: siddharth1
        #     IMAGE_NAME: github-actions-nginx
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
        # environment variables at the STEP level
        #   env:
        #     CONTAINER_REGISTRY: docker.io
        #     DOCKER_USERNAME: siddharth1
        #     IMAGE_NAME: github-actions-nginx
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest